param([ValidateSet("Ryujinx", "Atmosphere")][string]$Target = "Ryujinx", [string]$ContentsRoot)
$ErrorActionPreference = "Stop"; Set-StrictMode -Version Latest
$PackageRoot = (Resolve-Path $PSScriptRoot).Path; $manifest = Get-Content -Raw (Join-Path $PackageRoot "PACKAGE_MANIFEST.json") | ConvertFrom-Json
if ($manifest.program_id -ne "010028600EBDA000") { throw "Unsupported package title ID." }
foreach ($line in @(Get-Content (Join-Path $PackageRoot "CHECKSUMS.txt"))) { if ($line -notmatch '^([0-9A-Fa-f]{64}) \*(.+)$') { throw "Malformed checksum: $line" }; $path = Join-Path $PackageRoot $Matches[2].Replace('/', '\'); if ((Get-FileHash -Algorithm SHA256 $path).Hash -ne $Matches[1].ToUpperInvariant()) { throw "Checksum mismatch: $($Matches[2])" } }
if ([string]::IsNullOrWhiteSpace($ContentsRoot)) { if ($Target -eq "Ryujinx") { $ContentsRoot = Join-Path $env:APPDATA "Ryujinx\mods\contents" } else { throw "Specify -ContentsRoot for Atmosphere." } }
$titleRoot = Join-Path ([IO.Path]::GetFullPath($ContentsRoot)) $manifest.program_id; $backupRoot = Join-Path $titleRoot (".bfcoop-backup\" + (Get-Date -Format "yyyyMMdd-HHmmss")); $backupCount = 0
foreach ($record in @($manifest.files)) { $prefix = "payload/contents/$($manifest.program_id)/"; if (-not ([string]$record.path).StartsWith($prefix, [StringComparison]::Ordinal)) { throw "Unexpected payload path: $($record.path)" }; $relative = ([string]$record.path).Substring($prefix.Length).Replace('/', '\'); $source = Join-Path $PackageRoot ([string]$record.path).Replace('/', '\'); $destination = Join-Path $titleRoot $relative; if (Test-Path $destination -PathType Leaf) { $backup = Join-Path $backupRoot $relative; New-Item -ItemType Directory -Force (Split-Path $backup) | Out-Null; Copy-Item $destination $backup -Force; $backupCount++ }; New-Item -ItemType Directory -Force (Split-Path $destination) | Out-Null; Copy-Item $source "$destination.bfcoop-new" -Force; Move-Item "$destination.bfcoop-new" $destination -Force }
Write-Host "Bowser's Fury Co-op $($manifest.version) installed for $Target."; Write-Host "Destination: $titleRoot"; if ($backupCount) { Write-Host "Backed up $backupCount existing file(s) under $backupRoot" }
