param([string]$BuildRoot, [string]$PackageRoot, [string]$ReportPath)
$ErrorActionPreference = "Stop"; Set-StrictMode -Version Latest
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path; $Version = (Get-Content -Raw (Join-Path $RepoRoot "VERSION")).Trim(); $ProgramId = "010028600EBDA000"; $Commit = "f698816d6e198afb0029ad5c07d55e7017a620fe"
if ([string]::IsNullOrWhiteSpace($BuildRoot)) { $BuildRoot = Join-Path $RepoRoot "artifacts\build" }; if ([string]::IsNullOrWhiteSpace($PackageRoot)) { $PackageRoot = Join-Path $RepoRoot "artifacts\package" }; if ([string]::IsNullOrWhiteSpace($ReportPath)) { $ReportPath = Join-Path $RepoRoot "artifacts\verify\verification-report.json" }
$build = Get-Content -Raw (Join-Path $BuildRoot "build-report.json") | ConvertFrom-Json; if ($build.status -ne "PASS" -or $build.version -ne $Version -or $build.program_id -ne $ProgramId -or $build.exlaunch_commit -ne $Commit -or -not $build.clean_build) { throw "Build identity verification failed." }
foreach ($name in @("subsdk9", "main.npdm", "exlaunch.elf")) { if (-not (Test-Path (Join-Path $BuildRoot $name) -PathType Leaf)) { throw "Missing build output: $name" } }
$patterns = @('(?i)[A-Z]:[\\/]+Users[\\/]+', '(?i)docs[\\/]evidence_graph', '\b(?:EVD|FND|ATT|HYP)-[A-Z0-9]', '\b(?:META-)?METHOD-[0-9]{3}\b', 'gh[opsu]_[A-Za-z0-9]{20,}')
foreach ($binary in @((Join-Path $BuildRoot "subsdk9"), (Join-Path $BuildRoot "exlaunch.elf"))) { $text = [Text.Encoding]::ASCII.GetString([IO.File]::ReadAllBytes($binary)); foreach ($pattern in $patterns) { if ([regex]::IsMatch($text, $pattern)) { throw "Private pattern found in $([IO.Path]::GetFileName($binary)): $pattern" } } }
$package = Get-Content -Raw (Join-Path $PackageRoot "package-report.json") | ConvertFrom-Json; if ($package.status -ne "PASS" -or $package.version -ne $Version -or $package.program_id -ne $ProgramId) { throw "Package identity verification failed." }; $zipPath = [string]$package.zip.path; if ((Get-FileHash -Algorithm SHA256 $zipPath).Hash -ne [string]$package.zip.sha256) { throw "Package ZIP hash mismatch." }
$unpack = Join-Path (Split-Path -Parent $ReportPath) "unpacked"; if (Test-Path $unpack) { Remove-Item $unpack -Recurse -Force }; New-Item -ItemType Directory -Force $unpack | Out-Null; Expand-Archive $zipPath $unpack
$top = @(Get-ChildItem $unpack -Directory); if ($top.Count -ne 1) { throw "Package must have one top-level directory." }; $expanded = $top[0].FullName; $pm = Get-Content -Raw (Join-Path $expanded "PACKAGE_MANIFEST.json") | ConvertFrom-Json; if ($pm.version -ne $Version -or $pm.program_id -ne $ProgramId -or $pm.exlaunch_commit -ne $Commit) { throw "Expanded package manifest mismatch." }
$installRoot = Join-Path (Split-Path -Parent $ReportPath) "install-tests"; if (Test-Path $installRoot) { Remove-Item $installRoot -Recurse -Force }; & (Join-Path $expanded "install.ps1") -Target Ryujinx -ContentsRoot (Join-Path $installRoot "ryujinx\contents"); & (Join-Path $expanded "install.ps1") -Target Atmosphere -ContentsRoot (Join-Path $installRoot "atmosphere\contents")
foreach ($target in @("ryujinx", "atmosphere")) { $installed = Join-Path $installRoot "$target\contents\$ProgramId\exefs\subsdk9"; if ((Get-FileHash $installed).Hash -ne (Get-FileHash (Join-Path $BuildRoot "subsdk9")).Hash) { throw "Installer test failed for $target." } }
New-Item -ItemType Directory -Force (Split-Path -Parent $ReportPath) | Out-Null; [ordered]@{ schema_version = 1; status = "PASS"; version = $Version; program_id = $ProgramId; exlaunch_commit = $Commit; installer_tests = @("Ryujinx", "Atmosphere"); zip_sha256 = [string]$package.zip.sha256 } | ConvertTo-Json -Depth 8 | Set-Content $ReportPath -Encoding UTF8
Write-Host "Bowser's Fury Co-op public verification: PASS"
